### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by bulolo** [klren0312/ZSpider#7]
npm i  后
npm run dev 报

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'

**Comment by klren0312** [comment]
改成阿里源呢

**Comment by klren0312** [comment]
```shell
npm install --registry=https://registry.npm.taobao.org
```

**Comment by klren0312** [comment]
# 已修复
monaco-editor与monaco-editor-webpack-plugin版本不对应导致无法安装
![image](https://user-images.githubusercontent.com/10903843/85199328-37d1a400-b321-11ea-958d-a2c2df4878e9.png)
